// 手绘像素角色精灵：猫娘"小玉"（字符串网格调色板定义，无外部素材）
// 96x96 坐姿垂钓 sprite（面向右侧水面；48x48 原稿经 EPX 2x 平滑放大 + 手工细节补丁，
// 管线见 tools/neko96.py），钓竿由场景代码程序化绘制
// 形象依据 reference-xiaoyu.jpg：奶油金发 + 三毛猫大黑斑、右耳花饰、红项圈金铃、
// 露肩白和服（黑金领口/袖口 + 碎花 + 黑金前片）、红腰带大金结、注连绳成对金铃红流苏

export type SpriteGrid = string[]

// 调色板
export const NEKO_PALETTE: Record<string, string> = {
  H: '#f7dd8e',
  h: '#d9a844',
  d: '#caa03e',
  i: '#fdf3c8',
  K: '#26262e',
  k: '#4a4a56',
  W: '#ffffff',
  E: '#f7a8c0',
  S: '#ffe9d2',
  s: '#eeb98f',
  u: '#f5b09a',
  Y: '#f2b134',
  y: '#ffe08a',
  B: '#1c1c26',
  M: '#c95a5a',
  w: '#f8f4ea',
  q: '#c9bd9e',
  G: '#e8b93e',
  g: '#b98a24',
  L: '#ffd24a',
  P: '#ffb3c8',
  p: '#f2d45c',
  O: '#23232e',
  R: '#d64545',
  X: '#a83232',
  T: '#f4f4f8',
  t: '#d5d5e2',
  r: '#c0392b',
  b: '#7e2418',
  F: '#ff9ebb',
  C: '#7fb3ff',
  v: '#6aa84f',
  a: '#4fc3a1',
}

// 96x96 坐姿垂钓 sprite（面向右侧水面）
export const NEKO_IDLE: SpriteGrid = [
  '................................................................................................',
  '............................................................................BB..................',
  '...........................................................................BCCB.................',
  '..................................BB........................BB.....BBBB...BCCCCB................',
  '.................................BWWB......................BWWB..BBKCCWBBBCCWWCCB...............',
  '............................BB..BWWWWB.....................BWWWBBKKKCWWWWBCCWWCCB...............',
  '...........................BCCB.BWWWWBB.....................BWBWKKKKWWppWWBCCCCB................',
  '..........................BCCCCBWWWWWWWB........BB...........BWKKKKKKWppWWBBCCB.................',
  '.........................BCCWWCCWWEEWWWBB......BHHB........BBKKKKKKKKWWWWBBFFFB.................',
  '.........................BCCWWCCWEEEEWWWWBBBBBBHHHHBBBBBBBBKKKKKKKKKKKKWBFFFFFBB................',
  '..........................BCCCCWWEEEEWWWWWHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKFFMMFFvvB...............',
  '...........................BCCWEEEEEEEEWWWWHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKFMMFFvvB...............',
  '..........................BWWWEEEEEEEEEEWWWWHHHHHHHHHKKKKKKKKKKKKKKKvvKKKFFFFFBB................',
  '.........................BWWWWEEEEEEEEEEWWWWHHHHHHHHKKKKKKKKKKKKKKKKvvKKKKFFFB..................',
  '.........................BWWWWWWWWWWWWWWWWWWHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '..........................BWWWWWWWWWWWWWWWWHHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '...........................BBBHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKppBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKpBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKBBCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKB.BCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKKKB..BB....................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKB.........................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKKhKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHhhhhHHHHHHKKKKKKhhhhKKKKKKKKHB........................',
  '.........................BHHHHHHHHHHHHHHHHhhhhHHHHHHHKKKKKhhhhKKKKKKKKHHB.......................',
  '.........................BHHHHHHhhHHHHHHhhHhHHHHhhHHHKKKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHHhhHHhHHHhhHHHHHKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHSSSBBYhSHHHHSSHHHSSBBYKKKSSKKKHhhB.......................',
  '.........................BHHHHHhhhhhHSSSSSBBYYSSHHSSSSHHSSBBYYKKSSSKHHhhB.......................',
  '.........................BHHHHHhhhhhSSSSSSBBYYBSSSSSSSSSSSBBYYBBSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSWSBBYYBBSSSSSSSSSSBBYYBWSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSSHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBBYYBBSSSSSSSSSSBBYYuuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBBYYBSSSSSSSSSSSSBYYuuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhhBBhhhhSSSSSSSSSSSBBWWBBSSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhB..BBhhhSSSSSSSSSSBBWWBBSSSSSSSSSSHHHHhhB.......................',
  '.........................BHHHHhhB....BBBBSSSSSSSSSSSMMSSSSSSSSSSSBHHHHhhB.......................',
  '.........................BHHHhhB.........BBSSSSSSSSSMMSSSSSSSSSBB.BHHHhhB.......................',
  '.........................BHHhhhB..........BSSSSSSSSSsssSSSSSSSSB.BhHHHhhB.......................',
  '..........................BHhhhB.........BBBSSSSSSSSSsssSSSSSBB...BhHHhB........................',
  '..........................BHHHB.........BXRRRRRRRRRSSSRRXXBBB......BHHB.........................',
  '...........................BHHB..BBBBBBBXXRRRRRRRRRRSSSRXXBBBBBBB..BHHB.........................',
  '...........................BFFB.BSSSSSSSSSSSSSggLLggSSSSSSSSSSSSSB.BFFB.........................',
  '..........................BFFFFBSSSSSSSSSSSSSSgLLLLgSSSSSSSSSSSSSSBFFFFB........................',
  '..........................BFppFFsSSSSSSSSSSSSSLLLLLLSSSSSSSSSSSSSsFFppFB........................',
  '.........................BFFppFFssSSSSSSSSSSSSSLLLLSSSSSSSSSSSSSssFFppFFB.......................',
  '........................BRXXGGGGGGGGGGGSSSSSSSSSBBSSSSSSSGGGGGGGGGGGGGXXRB......................',
  '.......................BRRRXGGGGGGGGGGGGSSSSSSSSBBSSSSSSGGGGGGGGGGGGGGXRRRB.....................',
  '.......................BRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRB.....................',
  '.....................BBRRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRRBB...................',
  '....................BXRRRXBBBBBBGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXRRRXB..................',
  '.................BBBXXRRXXB....BGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXXRRXXB.................',
  '................BqwwwwwwwwwB..BqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqB................',
  '...............BqqwwwwwwwwwwBBqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqB...............',
  '..............BGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGB..............',
  '.............BGGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGGB.............',
  '.............BGGqqPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwPPwwwwqqGGB.............',
  '.............BGGqPPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwPPPwwwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORGGGLLGGLLGGGROOwwPPqwppwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORRGLLLGGLLLGRRROwwPPqwppwwqqGGB.............',
  '.............BGGqPPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLLGRRGLLLRRRRwwwPqPwwwwqqGGB.............',
  '.............BGGqqPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLGGRRGGLLRRRRwwwwqPwwwwqqGGB.............',
  '.............BGGqqwwwwPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwwPPqqGGB.............',
  '.............BGGqqwwwPPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwPPPqqGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOOGGggGGggGGOOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOGGGggGGggGGGOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwwPPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwwwPwPqqGGB.............',
  '..............BGGqwwwwPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwGwwwwwwwPPqGGB..............',
  '..............BGGGGGGGGGGGGGBBqqwwwwwwwwppwwwwRRwwRRwwwwwwOOOOOOOOwGwGGGGGGGGGGGGB..............',
  '...............BGGGGGGGGGGGGBBqqwwwwwwwwqpwwwwRRwwqRwwwwwwOOOOOOOOwwGGGGGGGGGGGGB...............',
  '...............BOOOOOOOOOOOOBBqqwwwwwwwwwqwwwwRRwwqRwwwwwwOOGGOOppwwOOOOOOOOOOOOB...............',
  '................BOOOOOOOOOOB.BqqwwwwwwwwwwqwwwRRwwqRwwwwwwOOGGOpppwwwOOOOOOOOOOB................',
  '.................BBBRRXXRRB..BqqwwwwwwwwwwwqwaaawwqCCwwwwwOOOOpppOwwwwqqRRXXRRB.................',
  '...................BRXXXXRB..BqqwwwwwwwwwwwwaaaawwqCCCwwwwOOOOppOOwwwwqqRXXXXRB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwpaaawwWCCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwppaawwWWCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BRXXXXRB..BGGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRXXXXRB.................',
  '...................BRRXXRRB...BGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRRXXRRB.................',
  '..................BgggBBgggB...BBBBBBBBBBBBBTTTTTTttBBBBTTTTTTttBBBBggggBBggggB.................',
  '.................BggggBBggggB.........BWB..BTTTTTTttB.BWTTTTTTttB..BggggBBggggB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BggBBBBggBBB..........B...BTTTTTTttB..BTTTTTTttB..BggBBBBggBBB.................',
  '.................BggBBBBggBB...............BTTTTTTttB..BTTTTTTttB..BggBBBBggBB..................',
  '.................BRRXXRRXXB................BTTTTTbttB..BTTTTTbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB................BTTTTbbttBBBBTTTTbbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB...............BrrrrrrrrrrrrrrrrrrrrrrB.BRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BrrrrrrrrrrrrrrrrrrrrrrrrBBRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BbbbbbbbbbbbbbbbbbbbbbbbbBBRRXXRRXXB...................',
  '..................BRXXRRXB................BbbbbbbbbbbbbbbbbbbbbbbB..BRXXRRXB....................',
]

// 钓到鱼时的兴奋姿势：闭眼笑 + 张嘴笑
export const NEKO_EXCITED: SpriteGrid = [
  '................................................................................................',
  '............................................................................BB..................',
  '...........................................................................BCCB.................',
  '..................................BB........................BB.....BBBB...BCCCCB................',
  '.................................BWWB......................BWWB..BBKCCWBBBCCWWCCB...............',
  '............................BB..BWWWWB.....................BWWWBBKKKCWWWWBCCWWCCB...............',
  '...........................BCCB.BWWWWBB.....................BWBWKKKKWWppWWBCCCCB................',
  '..........................BCCCCBWWWWWWWB........BB...........BWKKKKKKWppWWBBCCB.................',
  '.........................BCCWWCCWWEEWWWBB......BHHB........BBKKKKKKKKWWWWBBFFFB.................',
  '.........................BCCWWCCWEEEEWWWWBBBBBBHHHHBBBBBBBBKKKKKKKKKKKKWBFFFFFBB................',
  '..........................BCCCCWWEEEEWWWWWHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKFFMMFFvvB...............',
  '...........................BCCWEEEEEEEEWWWWHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKFMMFFvvB...............',
  '..........................BWWWEEEEEEEEEEWWWWHHHHHHHHHKKKKKKKKKKKKKKKvvKKKFFFFFBB................',
  '.........................BWWWWEEEEEEEEEEWWWWHHHHHHHHKKKKKKKKKKKKKKKKvvKKKKFFFB..................',
  '.........................BWWWWWWWWWWWWWWWWWWHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '..........................BWWWWWWWWWWWWWWWWHHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '...........................BBBHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKppBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKpBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKBBCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKB.BCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKKKB..BB....................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKB.........................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKKhKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHhhhhHHHHHHKKKKKKhhhhKKKKKKKKHB........................',
  '.........................BHHHHHHHHHHHHHHHHhhhhHHHHHHHKKKKKhhhhKKKKKKKKHHB.......................',
  '.........................BHHHHHHhhHHHHHHhhHhHHHHhhHHHKKKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHHhhHHhHHHhhHHHHHKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHSSSHHHhSHHHHSSHHHSSSKKKKKSSKKKHhhB.......................',
  '.........................BHHHHHhhhhhHSSSSSHHSSSSHHSSSSHHSSSSKKKSSSSKHHhhB.......................',
  '.........................BHHHHHhhhhhSSSSSSSSBBSSSSSSSSSSSSSSBBSSSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSSSSBBBBSSSSSSSSSSSSBBBBSSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSSSBBSSBBSSSSSSSSSSBBSSBBSSSSSHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSBBSSBBSSSSSSSSSSBBSSBBSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBBSSBBSSSSSSSSSSBBSSuuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBSSSBBSSSSSSSSSSBBSSSuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhhBBhhhhSSSSSSSSSSSSBWWWWBSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhB..BBhhhSSSSSSSSSSBBWWWWBBSSSSSSSSHHHHhhB.......................',
  '.........................BHHHHhhB....BBBBSSSSSSSSSMMMMMMBBSSSSSSSBHHHHhhB.......................',
  '.........................BHHHhhB.........BBSSSSSSSSMMMMMBSSSSSSBB.BHHHhhB.......................',
  '.........................BHHhhhB..........BSSSSSSSSSssssSSSSSSSB.BhHHHhhB.......................',
  '..........................BHhhhB.........BBBSSSSSSSSSsssSSSSSBB...BhHHhB........................',
  '..........................BHHHB.........BXRRRRRRRRRSSSRRXXBBB......BHHB.........................',
  '...........................BHHB..BBBBBBBXXRRRRRRRRRRSSSRXXBBBBBBB..BHHB.........................',
  '...........................BFFB.BSSSSSSSSSSSSSggLLggSSSSSSSSSSSSSB.BFFB.........................',
  '..........................BFFFFBSSSSSSSSSSSSSSgLLLLgSSSSSSSSSSSSSSBFFFFB........................',
  '..........................BFppFFsSSSSSSSSSSSSSLLLLLLSSSSSSSSSSSSSsFFppFB........................',
  '.........................BFFppFFssSSSSSSSSSSSSSLLLLSSSSSSSSSSSSSssFFppFFB.......................',
  '........................BRXXGGGGGGGGGGGSSSSSSSSSBBSSSSSSSGGGGGGGGGGGGGXXRB......................',
  '.......................BRRRXGGGGGGGGGGGGSSSSSSSSBBSSSSSSGGGGGGGGGGGGGGXRRRB.....................',
  '.......................BRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRB.....................',
  '.....................BBRRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRRBB...................',
  '....................BXRRRXBBBBBBGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXRRRXB..................',
  '.................BBBXXRRXXB....BGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXXRRXXB.................',
  '................BqwwwwwwwwwB..BqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqB................',
  '...............BqqwwwwwwwwwwBBqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqB...............',
  '..............BGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGB..............',
  '.............BGGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGGB.............',
  '.............BGGqqPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwPPwwwwqqGGB.............',
  '.............BGGqPPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwPPPwwwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORGGGLLGGLLGGGROOwwPPqwppwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORRGLLLGGLLLGRRROwwPPqwppwwqqGGB.............',
  '.............BGGqPPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLLGRRGLLLRRRRwwwPqPwwwwqqGGB.............',
  '.............BGGqqPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLGGRRGGLLRRRRwwwwqPwwwwqqGGB.............',
  '.............BGGqqwwwwPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwwPPqqGGB.............',
  '.............BGGqqwwwPPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwPPPqqGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOOGGggGGggGGOOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOGGGggGGggGGGOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwwPPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwwwPwPqqGGB.............',
  '..............BGGqwwwwPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwGwwwwwwwPPqGGB..............',
  '..............BGGGGGGGGGGGGGBBqqwwwwwwwwppwwwwRRwwRRwwwwwwOOOOOOOOwGwGGGGGGGGGGGGB..............',
  '...............BGGGGGGGGGGGGBBqqwwwwwwwwqpwwwwRRwwqRwwwwwwOOOOOOOOwwGGGGGGGGGGGGB...............',
  '...............BOOOOOOOOOOOOBBqqwwwwwwwwwqwwwwRRwwqRwwwwwwOOGGOOppwwOOOOOOOOOOOOB...............',
  '................BOOOOOOOOOOB.BqqwwwwwwwwwwqwwwRRwwqRwwwwwwOOGGOpppwwwOOOOOOOOOOB................',
  '.................BBBRRXXRRB..BqqwwwwwwwwwwwqwaaawwqCCwwwwwOOOOpppOwwwwqqRRXXRRB.................',
  '...................BRXXXXRB..BqqwwwwwwwwwwwwaaaawwqCCCwwwwOOOOppOOwwwwqqRXXXXRB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwpaaawwWCCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwppaawwWWCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BRXXXXRB..BGGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRXXXXRB.................',
  '...................BRRXXRRB...BGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRRXXRRB.................',
  '..................BgggBBgggB...BBBBBBBBBBBBBTTTTTTttBBBBTTTTTTttBBBBggggBBggggB.................',
  '.................BggggBBggggB.........BWB..BTTTTTTttB.BWTTTTTTttB..BggggBBggggB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BggBBBBggBBB..........B...BTTTTTTttB..BTTTTTTttB..BggBBBBggBBB.................',
  '.................BggBBBBggBB...............BTTTTTTttB..BTTTTTTttB..BggBBBBggBB..................',
  '.................BRRXXRRXXB................BTTTTTbttB..BTTTTTbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB................BTTTTbbttBBBBTTTTbbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB...............BrrrrrrrrrrrrrrrrrrrrrrB.BRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BrrrrrrrrrrrrrrrrrrrrrrrrBBRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BbbbbbbbbbbbbbbbbbbbbbbbbBBRRXXRRXXB...................',
  '..................BRXXRRXB................BbbbbbbbbbbbbbbbbbbbbbbB..BRXXRRXB....................',
]

export const PIG_PALETTE: Record<string, string> = {
  P: '#ffb3c8',
  p: '#ff9eb8',
  B: '#14141c',
  n: '#ff7ba3',
  W: '#ffffff',
}

// 粉色猪猪气球
export const PIG_BALLOON: SpriteGrid = [
  '....PP......PP....',
  '...PPPP....PPPP...',
  '...PPPPPPPPPPPP...',
  '..PPPPPPPPPPPPPP..',
  '..PPBPPPPPPPPBPP..',
  '..PPPPPnnnnPPPPP..',
  '..PPPPPnnnnPPPPP..',
  '..PPPPPPPPPPPPPP..',
  '...PPPPPPPPPPPP...',
  '....PPPPPPPPPP....',
]

/** 通用像素精灵绘制：'.' 为透明。自动容忍行宽不一致。 */
export function drawSprite(
  ctx: CanvasRenderingContext2D,
  grid: SpriteGrid,
  palette: Record<string, string>,
  x: number,
  y: number,
  scale: number,
) {
  for (let r = 0; r < grid.length; r++) {
    const row = grid[r]
    for (let c = 0; c < row.length; c++) {
      const ch = row[c]
      if (ch === '.') continue
      const color = palette[ch]
      if (!color) continue
      ctx.fillStyle = color
      ctx.fillRect(x + c * scale, y + r * scale, scale, scale)
    }
  }
}

// ---------- 结缘金铃神社（32x36，5 层递进叠加，离线预览调稿见 tools/shrine_preview.py） ----------
export const SHRINE_PALETTE: Record<string, string> = {
  S: '#8a8a9a', // 石头
  s: '#66667a', // 石暗
  W: '#b0b0c0', // 石亮
  R: '#c0392b', // 朱红柱
  r: '#8f2a20', // 柱暗/灯框
  w: '#f5efe0', // 墙白
  q: '#d8cfb8', // 墙影
  D: '#2c2c38', // 屋顶
  d: '#4a4a5e', // 瓦楞高光
  G: '#e8b93e', // 金饰
  L: '#ffd24a', // 金铃
  N: '#3a2a1c', // 木门/供箱
  T: '#d64545', // 注连绳
  F: '#ffffff', // 纸垂
  E: '#ff9d5c', // 灯笼暖光
}

// 阶段 1 地基：石台（两级台阶 + 石纹 + 水底阴影）
export const SHRINE_L1: SpriteGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '......WSSSSSSSSSSSSSSSSSSW......',
  '....SSSSSSSSSSSSSSSSSSSSSSSS....',
  '....WSSsSSWSSsSSWSSsSSWSSsSS....',
  '...SSSSSSSSSSSSSSSSSSSSSSSSSS...',
  '...SSsSSSsSSSsSSSsSSSsSSSsSSS...',
  '...ssssssssssssssssssssssssss...',
  '...ssssssssssssssssssssssssss...',
]

// 阶段 2 支柱：朱红双柱 + 双层横梁
export const SHRINE_L2: SpriteGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '......RR................RR......',
  '......Rr................Rr......',
  '......RRRRRRRRRRRRRRRRRRRR......',
  '......RRRRRRRRRRRRRRRRRRRR......',
  '......RR................RR......',
  '......Rr................Rr......',
  '......RR................RR......',
  '......RR................RR......',
  '......RR................RR......',
  '......Rr................Rr......',
  '......RR................RR......',
  '......RR................RR......',
  '......RR................RR......',
  '......Rr................Rr......',
  '......RR................RR......',
  '......RR................RR......',
  '......Rr................Rr......',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
]

// 阶段 3 主体：白墙 + 黑门 + 金门环 + 金线脚
export const SHRINE_L3: SpriteGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '........qqqqqqqqqqqqqqqq........',
  '........qwwwwwwwwwwwwwww........',
  '........qwwwwwwwwwwwwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNGGNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qwwwNNNNNNNNwwww........',
  '........qqqqNNNNNNNNqqqq........',
  '........qqqqNNNNNNNNqqqq........',
  '........GGGGGGGGGGGGGGGG........',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
]

// 阶段 4 房顶：歇山大屋顶 + 瓦楞 + 金鸱吻
export const SHRINE_L4: SpriteGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '.............GGGGGG.............',
  '...........DDDDDDDDDD...........',
  '...........DDDDDDDDDD...........',
  '..........DDDDDDDDDDDD..........',
  '........DDDDDDDDDDDDDDDD........',
  '........dDDDdDDDdDDDdDDD........',
  '.......DDDDDDDDDDDDDDDDDD.......',
  '.......DDDDDDDDDDDDDDDDDD.......',
  '.....DddDDddDDddDDddDDddDDdd....',
  '.....DDDDDDDDDDDDDDDDDDDDDD.....',
  '....DDDDDDDDDDDDDDDDDDDDDDDD....',
  '...GDDDDDDDDDDDDDDDDDDDDDDDDG...',
  '....D......................D....',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
]

// 阶段 5 装饰：檐角金铃 + 注连绳纸垂 + 双吊灯 + 供箱
export const SHRINE_L5: SpriteGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '..........G...........G.........',
  '......L.TrrrTTTTTTTTTrrrL.......',
  '.....LLL.EEE.F..F..F.EEELL......',
  '......L..EEE..F..F..FEEEL.......',
  '.........rrr.........rrr........',
  '................................',
  '................................',
  '................................',
  '................................',
  '............DDDDDDDD............',
  '............NGNGNGNN............',
  '............NGNGNGNN............',
  '............NNNNNNNN............',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
]

/** 神社五层：第 n 阶段 = 叠加绘制前 n 层 */
export const SHRINE_LAYERS: SpriteGrid[] = [
  SHRINE_L1,
  SHRINE_L2,
  SHRINE_L3,
  SHRINE_L4,
  SHRINE_L5,
]

// ---------- 交易所横幅：小玉炒股（96x48，C 款赛璐璐风格，管线见 tools/stock_art.py） ----------
export const NEKO_STOCK_PALETTE: Record<string, string> = {
  ...NEKO_PALETTE,
  '0': '#141c2e',
  '1': '#26262e',
  '2': '#8a6547',
  '3': '#6e4f36',
  '5': '#3ddc84',
  '6': '#7db8e8',
}

export const NEKO_STOCK: SpriteGrid = [
  '....................BHHBBBB..........BHHBBFWFB..................................................',
  '.....................BHHHHHBB..BBBBB.BEBHWCFvB..................................................',
  '......................BEBBBHHBBHHHHHBHHHKBBBB...................................................',
  '......................BHEBBHHHHHHHHHKKKKKKKB....................................................',
  '.......................BHEHHHHHHHHHKKKKKKKKKB...................................................',
  '........................BHHHHHHHHHHKKKKKKKKKB...............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.....',
  '........................BHHHHHHHHHHHHHKKKKKKKB.............B1111111111111111111111111111111B....',
  '.......................BHHHHHHHHHHHHHHHKKKKKB..............B111111111111111111111111R111111B....',
  '.......................BHHHHHHHHHHHHHHHSSKKKB..............B1100000000000000R00000000000011B....',
  '......................BHHHHHHHHHHHHHSSSSSSSHB..............B11066666666000000000000RRR00011B....',
  '......................BHHHHHHHHHHHHSSSSSSSSSB..............B11060000R000000RRR00000RRR00011B....',
  '......................BHHHHHHHHHHHHSSSSSBSSSB..............B110000000000000RRR00000RRR00011B....',
  '......................BhhhhhhhHHHHSSSSSSBGSSSB.............B1100000RRR00000RRR00500RRR00011B....',
  '......BBBBBBBB........BhhhhhhhhhhHSSSSSSBSSSSB.............B1100000RRR00000RRR00000RRR00011B....',
  '.....B11111111B.......BhhhhhhhhhhhSSSSSSBSSSSB.............B1100000RRR00500RRR05550RRR00011B....',
  '.....B11111111B.......BhhhhhhhhhhhHSSSSSSSuuB..............B1100000RRR00000RRR05550RRR00011B....',
  '.....B11111111B......BhhhhhhhhhhhhhSSSSSSSSMB..............B1100R00RRR05550RRR055500R000011B....',
  '.....B11111111B.......BhhhhhhhhhhhHHSSSSSSSB...............B1100000RRR05550RRR0555000000011B....',
  '.....B11111111B.......BhhhhhhhhhhhHHHHSSSBB................B110RRR0RRR055500R00555000000011B....',
  '.....B11111111B........BhhhhhhhhhHHHHHHBB..................B110RRR0RRR055500000050000000011B....',
  '.....B11111111B.........BBBhhhRHHHHHRRRRB..................B110RRR0RRR055500000000000000011B....',
  '.....B11111111B............BRRRRRRRRRRRRB..................B110RRR00R0055500000000000000011B....',
  '.....B11111111B............BwwwwwWLwwwwB...................B110RRR0000005000000000000000011B....',
  '.....B11111111B..........BBwwwwwwLLwwwwwBB.................B110RRR0000000000000000000000011B....',
  '.....B11111111B.........BwwwwwwwwwwwwwwwwwB................B110RRR0000000000000000000000011B....',
  '.....B11111111B.........BwwwwwwwwwwwwwwwwwBB...............B1100R00000000000000000000000011B....',
  '.....B11111111B........BwwwwwwwwwwwwwwwwwwwwBB.............B1100000000000000000000000000011B....',
  '.....B11111111B........BwwwwwwwwwwwwwwwwwwwwwwBB...........B1111111111111111111111111111111B....',
  '.....B11111111B.......BwwwwwwwwwwwwwwwwwwwwwwwwwBB.........B1111111111111111111111111111111B....',
  '.....B11111111B.......BwwwwwwwwwwwwwwwwwwwwwBwwwwwBBBBB.....BBBBBBBBBBBBB11BBBBBBBBBBBBBBBB.....',
  '.....B11111111B......BwwwwwwwwwwwwwwwwwwwwwwBBBwwwwwSSSB................B11B....................',
  '.....B11111111B......BwwwwwwRRRRRRRRRRRRRwwB..BBBwwwSSSBBBB...........BBB11BBB..................',
  '.....B11111111B...BBBwwwwwwwRRRRRRRRRRRRRwwBBB1313131313131BBBBBBBBBBB11111111BBBBBBBBBBBBBBBB..',
  '.....B11111111B..B2222222222222222222222222222222222222222222222222222111111112222222222222222B.',
  '.....B1111111HHB.B2222222222222222222222222222222222222222222222222222222222222222222222222222B.',
  '......BB1111HHHB.B2222222222222222222222222222222222222222222222222222222222222222222222222222B.',
  '.......B1111HHB..B3333333333333333333333333333333333333333333333333333333333333333333333333333B.',
  '.......B111HHHB..B3333333333333333333333333333333333333333333333333333333333333333333333333333B.',
  '.......B11HHHB....BB333BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB333BBB..',
  '.......B1BHHB......B333B...............................................................B333B....',
  '.......B1HHHB......B333B...............................................................B333B....',
  '......B.BHHB.......B333B...............................................................B333B....',
  '.....BWBHHHB.......B333B...............................................................B333B....',
  '......BWHHB........B333B...............................................................B333B....',
  '.......BBB.........B333B...............................................................B333B....',
  '....................BBB.................................................................BBB.....',
  '................................................................................................',
  '................................................................................................',
]
