// 精细版小玉 · 款式 C：赛璐璐强勾线（96x96 字符串网格 + 调色板，选自审后并入 sprite.ts）
type SpriteGrid = string[]

export const NEKO_PALETTE_VARIANT_C: Record<string, string> = {
  H: '#f7dd8e',
  h: '#d9a844',
  d: '#caa03e',
  i: '#fdf3c8',
  K: '#26262e',
  k: '#4a4a56',
  W: '#ffffff',
  E: '#f7a8c0',
  S: '#ffe9d2',
  s: '#eeb98f',
  u: '#f5b09a',
  Y: '#f2b134',
  y: '#ffe08a',
  B: '#1c1c26',
  M: '#c95a5a',
  w: '#f8f4ea',
  q: '#c9bd9e',
  G: '#e8b93e',
  g: '#b98a24',
  L: '#ffd24a',
  P: '#ffb3c8',
  p: '#f2d45c',
  O: '#23232e',
  R: '#d64545',
  X: '#a83232',
  T: '#f4f4f8',
  t: '#d5d5e2',
  r: '#c0392b',
  b: '#7e2418',
  F: '#ff9ebb',
  C: '#7fb3ff',
  v: '#6aa84f',
  a: '#4fc3a1',
}

export const NEKO_IDLE_VARIANT_C: SpriteGrid = [
  '................................................................................................',
  '............................................................................BB..................',
  '...........................................................................BCCB.................',
  '..................................BB........................BB.....BBBB...BCCCCB................',
  '.................................BWWB......................BWWB..BBKCCWBBBCCWWCCB...............',
  '............................BB..BWWWWB.....................BWWWBBKKKCWWWWBCCWWCCB...............',
  '...........................BCCB.BWWWWBB.....................BWBWKKKKWWppWWBCCCCB................',
  '..........................BCCCCBWWWWWWWB........BB...........BWKKKKKKWppWWBBCCB.................',
  '.........................BCCWWCCWWEEWWWBB......BHHB........BBKKKKKKKKWWWWBBFFFB.................',
  '.........................BCCWWCCWEEEEWWWWBBBBBBHHHHBBBBBBBBKKKKKKKKKKKKWBFFFFFBB................',
  '..........................BCCCCWWEEEEWWWWWHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKFFMMFFvvB...............',
  '...........................BCCWEEEEEEEEWWWWHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKFMMFFvvB...............',
  '..........................BWWWEEEEEEEEEEWWWWHHHHHHHHHKKKKKKKKKKKKKKKvvKKKFFFFFBB................',
  '.........................BWWWWEEEEEEEEEEWWWWHHHHHHHHKKKKKKKKKKKKKKKKvvKKKKFFFB..................',
  '.........................BWWWWWWWWWWWWWWWWWWHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '..........................BWWWWWWWWWWWWWWWWHHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLLB...................',
  '...........................BBBHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKppBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKpBBLLB...................',
  '............................BHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKBBCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKB.BCCB...................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKKKB..BB....................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKhKKKKKKKKKKKKKKB.........................',
  '...........................BHHHHHHHHHHHHHHHHHHHHHHHHKKKKhKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKB.........................',
  '..........................BHHHHHHHHHHHHHHHhhhhHHHHHHKKKKKKhhhhKKKKKKKKHB........................',
  '.........................BHHHHHHHHHHHHHHHHhhhhHHHHHHHKKKKKhhhhKKKKKKKKHHB.......................',
  '.........................BHHHHHHhhHHHHHHhhHhHHHHhhHHHKKKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHHhhHHhHHHhhHHHHHKKKKKKKKKKKKKKKhhB.......................',
  '.........................BHHHHHHhhhHHHHSSSBBYhSHHHHSSHHHSSBBYKKKSSKKKHhhB.......................',
  '.........................BHHHHHhhhhhHSSSSSBBYYSSHHSSSSHHSSBBYYKKSSSKHHhhB.......................',
  '.........................BHHHHHhhhhhSSSSSSBBYYBSSSSSSSSSSSBBYYBBSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSWSBBYYBBSSSSSSSSSSBBYYBWSSSSSShhB.......................',
  '.........................BHHHHhhhhhhhSSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSSHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBBYYBBSSSSSSSSSSBBYYuuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhuuuuBBYYBSSSSSSSSSSSSBYYuuuuSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHhhB.......................',
  '.........................BHHHHhhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhhBBhhhhSSSSSSSSSSSBBWWBBSSSSSSSSSSSHHHhhB.......................',
  '.........................BHHHHhhB..BBhhhSSSSSSSSSSBBWWBBSSSSSSSSSSHHHHhhB.......................',
  '.........................BHHHHhhB....BBBBSSSSSSSSSSSMMSSSSSSSSSSSBHHHHhhB.......................',
  '.........................BHHHhhB.........BBSSSSSSSSSMMSSSSSSSSSBB.BHHHhhB.......................',
  '.........................BHHhhhB..........BSSSSSSSSSsssSSSSSSSSB.BhHHHhhB.......................',
  '..........................BHhhhB.........BBBSSSSSSSSSsssSSSSSBB...BhHHhB........................',
  '..........................BHHHB.........BXRRRRRRRRRSSSRRXXBBB......BHHB.........................',
  '...........................BHHB..BBBBBBBXXRRRRRRRRRRSSSRXXBBBBBBB..BHHB.........................',
  '...........................BFFB.BSSSSSSSSSSSSSggLLggSSSSSSSSSSSSSB.BFFB.........................',
  '..........................BFFFFBSSSSSSSSSSSSSSgLLLLgSSSSSSSSSSSSSSBFFFFB........................',
  '..........................BFppFFsSSSSSSSSSSSSSLLLLLLSSSSSSSSSSSSSsFFppFB........................',
  '.........................BFFppFFssSSSSSSSSSSSSSLLLLSSSSSSSSSSSSSssFFppFFB.......................',
  '........................BRXXGGGGGGGGGGGSSSSSSSSSBBSSSSSSSGGGGGGGGGGGGGXXRB......................',
  '.......................BRRRXGGGGGGGGGGGGSSSSSSSSBBSSSSSSGGGGGGGGGGGGGGXRRRB.....................',
  '.......................BRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRB.....................',
  '.....................BBRRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRRBB...................',
  '....................BXRRRXBBBBBBGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXRRRXB..................',
  '.................BBBXXRRXXB....BGGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGGBBBBBBXXRRXXB.................',
  '................BqwwwwwwwwwB..BqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqB................',
  '...............BqqwwwwwwwwwwBBqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqB...............',
  '..............BGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGB..............',
  '.............BGGqqwwwwwwwwwwBBqqwwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqGGB.............',
  '.............BGGqqPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwPPwwwwqqGGB.............',
  '.............BGGqPPPwwwwwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwPPPwwwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORGGGLLGGLLGGGROOwwPPqwppwwqqGGB.............',
  '.............BGGPPwwppwqwwwwBBOOOOOOOOOOOOOOOOOOOOOORRGLLLGGLLLGRRROwwPPqwppwwqqGGB.............',
  '.............BGGqPPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLLGRRGLLLRRRRwwwPqPwwwwqqGGB.............',
  '.............BGGqqPPwwwqwwwwBBRRRRRRPPRRRRRRRRRRRRppRRLLGGRRGGLLRRRRwwwwqPwwwwqqGGB.............',
  '.............BGGqqwwwwPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwwPPqqGGB.............',
  '.............BGGqqwwwPPqwwwwBBRRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwPPPqqGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOOGGggGGggGGOOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwPPwwppwwBBOOOOOOOOOOOOOOOOOOOOOOOGGGggGGggGGGOOOwwwwwwPPwwppGGB.............',
  '.............BGGqqwwwPPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwwwPwPqqGGB.............',
  '..............BGGqwwwwPPwwwwBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwGwwwwwwwPPqGGB..............',
  '..............BGGGGGGGGGGGGGBBqqwwwwwwwwppwwwwRRwwRRwwwwwwOOOOOOOOwGwGGGGGGGGGGGGB..............',
  '...............BGGGGGGGGGGGGBBqqwwwwwwwwqpwwwwRRwwqRwwwwwwOOOOOOOOwwGGGGGGGGGGGGB...............',
  '...............BOOOOOOOOOOOOBBqqwwwwwwwwwqwwwwRRwwqRwwwwwwOOGGOOppwwOOOOOOOOOOOOB...............',
  '................BOOOOOOOOOOB.BqqwwwwwwwwwwqwwwRRwwqRwwwwwwOOGGOpppwwwOOOOOOOOOOB................',
  '.................BBBRRXXRRB..BqqwwwwwwwwwwwqwaaawwqCCwwwwwOOOOpppOwwwwqqRRXXRRB.................',
  '...................BRXXXXRB..BqqwwwwwwwwwwwwaaaawwqCCCwwwwOOOOppOOwwwwqqRXXXXRB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwpaaawwWCCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BXXRRXXB..BqqwwwwwwwwwwwwppaawwWWCCwwwwOOGGOOOOwwwwqqXXRRXXB.................',
  '...................BRXXXXRB..BGGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRXXXXRB.................',
  '...................BRRXXRRB...BGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRRXXRRB.................',
  '..................BgggBBgggB...BBBBBBBBBBBBBTTTTTTttBBBBTTTTTTttBBBBggggBBggggB.................',
  '.................BggggBBggggB.........BWB..BTTTTTTttB.BWTTTTTTttB..BggggBBggggB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BLLLLBBLLLLB.........BWB..BTTTTTTttB.BWTTTTTTttB..BLLLLBBLLLLB.................',
  '.................BggBBBBggBBB..........B...BTTTTTTttB..BTTTTTTttB..BggBBBBggBBB.................',
  '.................BggBBBBggBB...............BTTTTTTttB..BTTTTTTttB..BggBBBBggBB..................',
  '.................BRRXXRRXXB................BTTTTTbttB..BTTTTTbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB................BTTTTbbttBBBBTTTTbbttB..BRRXXRRXXB...................',
  '.................BRRXXRRXXB...............BrrrrrrrrrrrrrrrrrrrrrrB.BRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BrrrrrrrrrrrrrrrrrrrrrrrrBBRRXXRRXXB...................',
  '.................BRRXXRRXXB..............BbbbbbbbbbbbbbbbbbbbbbbbbBBRRXXRRXXB...................',
  '..................BRXXRRXB................BbbbbbbbbbbbbbbbbbbbbbbB..BRXXRRXB....................',
]
