// 精细版小玉 · 款式 D：高密度细节（96x96 字符串网格 + 调色板，选自审后并入 sprite.ts）
type SpriteGrid = string[]

export const NEKO_PALETTE_VARIANT_D: Record<string, string> = {
  H: '#f7dd8e',
  h: '#e6bd5a',
  d: '#caa03e',
  i: '#fdf3c8',
  K: '#26262e',
  k: '#4a4a56',
  W: '#ffffff',
  E: '#f7a8c0',
  S: '#ffe9d2',
  s: '#f2cba4',
  u: '#f5b09a',
  Y: '#f2b134',
  y: '#ffe08a',
  B: '#1c1c26',
  M: '#c95a5a',
  w: '#f8f4ea',
  q: '#e4dcc9',
  G: '#e8b93e',
  g: '#b98a24',
  L: '#ffd24a',
  P: '#ffb3c8',
  p: '#f2d45c',
  O: '#23232e',
  R: '#d64545',
  X: '#a83232',
  T: '#f4f4f8',
  t: '#d5d5e2',
  r: '#c0392b',
  b: '#7e2418',
  F: '#ff9ebb',
  C: '#7fb3ff',
  v: '#6aa84f',
  a: '#4fc3a1',
  6: '#c98a1a',
}

export const NEKO_IDLE_VARIANT_D: SpriteGrid = [
  '................................................................................................',
  '................................................................................................',
  '............................................................................CC..................',
  '...........................................................................CCCC.................',
  '..................................WW........................WW.....KCCW...CCWWCC................',
  '.................................WWWW.......................WWW..KKKCWWWW.CCWWCC................',
  '............................CC...WWWW........................W.WKKKKWWppWW.CCCC.................',
  '...........................CCCC.WWWWWWW.......................WKKKKKKWppWW..CC..................',
  '..........................CCWWCCWWEEWWW.........HH...........KKKKKkkKWWWW..FFF..................',
  '..........................CCWWCCWEEEEWWWW......HHHH........KKKKKKkkkkKKW.FFFFF..................',
  '...........................CCCCWWEEEEWWWWWHHHHHHHHHHHHKKKKKKKKKKKkkkkKKKFFMMFFvv................',
  '............................CCWEEEEEEEEWWWWHHHHHHHHHHKKKKKKKKKKkkkkkkkkKKFMMFFvv................',
  '...........................WWWEEEEEEEEEEWWWWiiiiHHHHHKKKkkKKKKkkkkkkvvkKKFFFFF..................',
  '..........................WWWWEEEEEEEEEEWWWWiiiiHHHHKKKKkkKKKKkkkkkkvvkkKKFFF...................',
  '..........................WWWWWWWWWWWWWWWWWWHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLL....................',
  '...........................WWWWWWWWWWWWWiWWHHHiHHHHHKKKKKKKKKKKKKKKKKKLLKKLL....................',
  '..............................HHHHHHHHiiiiHHHHHiHHHHKKKKKKKKKKKKKKkkKKpp..LL....................',
  '.............................HHHHHHHHiHiiHiHHHHHiHHKhKKKKKKKKKKKKKkkKKKp..LL....................',
  '.............................HHHHhHHHHiHHHHHHHHHHiKKKhKKKKKKKKKKKKKKKKKK..CC....................',
  '............................HHHHHHhHHHHiHHHHHHHHHHiKKKhKKKKKKKKKKKKKKKK...CC....................',
  '............................HHHHHHHhHHHHiHHHHHHHHHHKKKdKKKKKKKKKKKKKKKK.........................',
  '............................HHHHHHHHhHHHHiHHHHHHHHHHKKKdKKKKKKKKKKKKKK..........................',
  '............................HhHHHHHHHHHHHHiHHHHHHHHHKKKKdKKKKKKKKKKKKK..........................',
  '...........................HHhHHHHHHHHHHHHHHhHHHHHHHKKKKKKKKKKKKKKKKKK..........................',
  '...........................HHhHHHHHHHHHHHHdddhHHHHHHKKKKKKddddKKKKKKKKH.........................',
  '..........................HHHhHHHHHHHHHHHHddddHHHHHHHKKKKKddddKKKKKKKKHH........................',
  '..........................HHHHHihhHHHHHHhhHhHHHHhhHHHKKKKKKKKKKKKKKKKKhh........................',
  '..........................HHHHHihhhHHHHBBBBHhHHHhhHHHHHKKKKKKKBBBBKKKKhh........................',
  '..........................HHHHHihhhHHHB6666ByhSHHHHSSHHHSSBByB6666BKKHhh........................',
  '..........................HHHHHhhhhhHSB6YYYYBySSHHSSSSHHSSBByB6YYYYBHHhh........................',
  '..........................HHHHHhhhhhSSBYWWYYBYBSSSSSSSSSSSBBYBYWWYYBSShh........................',
  '..........................HHHHhhhhhhhSBYWWYYBYBBSSSSSSSSSSBBYBYWWYYBSShh........................',
  '..........................HHHHhhhhhhhSBYYYYYBYBBSSSSSSSSSSBBYBYYYYYBSHhh........................',
  '..........................HHHHhhhhhhhhBYYYyYBYBBSSSSSSSSSSBBYBYYYyYBHHhh........................',
  '..........................HHHHhhhhhhhhBYYyyWBYBBSSSSSSSSSSBBYBYYyyWBHHhh........................',
  '..........................HHHHhhhhhhhhBYYYYYBYBSSSSSSSSSSSSBYBYYYYYBHHhh........................',
  '..........................HHHHhhhhhhhhSBBBBSSSSSSSSSSSSSSSSSSSBBBBSSHHhh........................',
  '..........................HHHHhhhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHHhh........................',
  '..........................HHHHhhh..hhhhSSSSSSSSSSSBBWWBBSSSSSSSSSSSHHHhh........................',
  '..........................HHHHhh.....hhhSSSSSSSSSSBBWWBBSSSSSSSSSSHHHHhh........................',
  '..........................HHHHhh.........SSSSSSSSSSSMMSSSSSSSSSSS.HHHHhh........................',
  '..........................HHHhh............SSSSSSSSSMMSSSSSSSSS....HHHhh........................',
  '..........................HHhdh............SSSSSSSSSsssSSSSSSSS...dHHHhh........................',
  '...........................Hhhd.............SSSSSSSSSsssSSSSS......dHHh.........................',
  '...........................HHH...........XRRRRRRRRRSSSRRXX..........HH..........................',
  '............................HH..........XXRRRRRRRRRRSSSRXX..........HH..........................',
  '............................FF...SSSSSSSSSSSSgyyyyggSSSSSSSSSSSSS...FF..........................',
  '...........................FFFF.SSSSSSSSSSSSSLLWLLLgSSSSSSSSSSSSSS.FFFF.........................',
  '...........................FppFFsSSSSSSSSSSSSGLLLGGLSSSSSSSSSSSSSsFFppF.........................',
  '..........................FFppFFssSSSSSSSSSSSSgGGgLSSSSSSSSSSSSSssFFppFF........................',
  '.........................RXXGGGGGGGGGGGSSSSSSSSSBBSSSSSSSGGGGGGGGGGGGGXXR.......................',
  '........................RRRXGGGGGGGGGGGGSSSSSSSSBBSSSSSSGGGGGGGGGGGGGGXRRR......................',
  '........................RRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRR......................',
  '.......................RRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRR.....................',
  '.....................XRRRX......GGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGG......XRRRX...................',
  '....................XXRRXX......GGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGG......XXRRXX..................',
  '.................qwwwwwwwww....qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwq.................',
  '................qqwwwwwwPwww..qqwwwwwwwwwwwwwPwwwwwwPwwwwwwPwwwwwwPwwwwwwPwwwwqq................',
  '...............GqqwwwwwPpPww..qqwwwwPPwwwwwwPpPwwwwPpPwwwwPpPwwwwPpPwwwwPpPwwwqqG...............',
  '..............GGqqwwwwwwPwww..qqwwwwPPwwwwwwwPwwwwwwPwwwwwwPwwwwwwPwwwwwwPwwwwqqGG..............',
  '..............GGqqPPwwwwwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwPPwwwwqqGG..............',
  '..............GGqPPPwwwwwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwPPPwwwwqqGG..............',
  '..............GGPPwwppwqwwww..OOOOOOOOOOOOOOOOOOOOOORGGGLLGGLLGGGROOwwPPqwppwwqqGG..............',
  '..............GGPPwwppwqwwww..OOOOOOOOOOOOOOOOOOOOOORRGLLLGGLLLGRRROwwPPqwppwwqqGG..............',
  '..............GGqPPPwwwqwwww..RRRRRRPPRRRRRRRRRRRRppRRLLLGRRGLLLRRRRwwwPqPwwwwqqGG..............',
  '..............GGqqPPwwwqwwww..RRRRRRPPRRRRRRRRRRRRppRRLLGGRRGGLLRRRRwwwwqPwwwwqqGG..............',
  '..............GGqqwwwwPqwwww..RRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwwPPqqGG..............',
  '..............GGqqwwwPPqwwww..RRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwwwqwwPPPqqGG..............',
  '..............GGqqwwPPwwppww..OOOOOOOOOOOOOOOOOOOOOOOOGGggGGggGGOOOOwwwwwwPPwwppGG..............',
  '..............GGqqwwPPwwppww..OOOOOOOOOOOOOOOOOOOOOOOGGGggGGggGGGOOOwwwwwwPPwwppGG..............',
  '..............GGqqwwwPPPwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwwwPwPqqGG..............',
  '...............GGqwwwwPPwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwGwwwwwwwPPqGG...............',
  '...............GGGGGGGGGGGGG..qqwwwwwwPwppwwwwRRwwRRwwwwwwOOOOOOOOwGwGGGGGGGGGGGG...............',
  '................GGGGGGGGGGGG..qqwwwwwPpPqpwwwwRRwwqRwwwwwwOOOOOOOOwwGGGGGGGGGGGG................',
  '................OOOOOOOOOOOO..qqwwwwwwPwwqwwwwRRwwqRwwwwwwOOGGOOppwwOOOOOOOOOOOO................',
  '.................OOOOOOOOOO...qqwwwwwwwwwwqwwwRRwwqRwwwwwwOOGGOpppwwwOOOOOOOOOO.................',
  '....................RRXXRR....qqwwwwwwwwwwwqwaaawwqCCwwwwwOOOOpppOwwwwqqRRXXRR..................',
  '....................RXXXXR....qqwwwwwwPwwwwwaaaawwqCCCwwwwOOOOppOOwwwwqqRXXXXR..................',
  '....................XXRRXX....qqwwwwwPpPwwwwpaaawwWCCCwwwwOOGGOOOOwwwwqqXXRRXX..................',
  '....................XXRRXX....qqwwwwwwPwwwwwppaawwWWCCwwwwOOGGOOOOwwwwqqXXRRXX..................',
  '....................RXXXXR....GGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRXXXXR..................',
  '....................RRXXRR.....GGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRRXXRR..................',
  '...................ggg..ggg.................TTTTTTtt....TTTTTTtt....gggg..gggg..................',
  '..................gggg..gggg...........W....TTTTTTtt...WTTTTTTtt....gggg..gggg..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................ggBB..ggBB................TTTTTTtt....TTTTTTtt....ggBB..ggBB..................',
  '..................ggBB..ggB.................TTTTTTtt....TTTTTTtt....ggBB..ggB...................',
  '..................RRXXRRXX..................TTTTTbtt....TTTTTbtt....RRXXRRXX....................',
  '..................RRXXRRXX..................TTTTbbtt....TTTTbbtt....RRXXRRXX....................',
  '..................RRXXRRXX.................rrrrrrrrrrrrrrrrrrrrrr...RRXXRRXX....................',
  '..................RRXXRRXX................rrrrrrrrrrrrrrrrrrrrrrrr..RRXXRRXX....................',
  '..................RRXXRRXX................bbbbbbbbbbbbbbbbbbbbbbbb..RRXXRRXX....................',
  '...................RXXRRX..................bbbbbbbbbbbbbbbbbbbbbb....RXXRRX.....................',
]
