// 精细版小玉 · 款式 B：16-bit 柔影晕染（96x96 字符串网格 + 调色板，选自审后并入 sprite.ts）
type SpriteGrid = string[]

export const NEKO_PALETTE_VARIANT_B: Record<string, string> = {
  H: '#f7dd8e',
  h: '#e6bd5a',
  d: '#caa03e',
  i: '#fdf3c8',
  K: '#26262e',
  k: '#4a4a56',
  W: '#ffffff',
  E: '#f7a8c0',
  S: '#ffe9d2',
  s: '#f2cba4',
  u: '#f5b09a',
  Y: '#f2b134',
  y: '#ffe08a',
  B: '#1c1c26',
  M: '#c95a5a',
  w: '#f8f4ea',
  q: '#e4dcc9',
  G: '#e8b93e',
  g: '#b98a24',
  L: '#ffd24a',
  P: '#ffb3c8',
  p: '#f2d45c',
  O: '#23232e',
  R: '#d64545',
  X: '#a83232',
  T: '#f4f4f8',
  t: '#d5d5e2',
  r: '#c0392b',
  b: '#7e2418',
  F: '#ff9ebb',
  C: '#7fb3ff',
  v: '#6aa84f',
  a: '#4fc3a1',
  1: '#eecd74',
  2: '#d8ae4c',
  3: '#f8dabb',
  4: '#eee8d9',
  5: '#383842',
}

export const NEKO_IDLE_VARIANT_B: SpriteGrid = [
  '................................................................................................',
  '................................................................................................',
  '............................................................................CC..................',
  '...........................................................................CCCC.................',
  '..................................WW........................WW.....KCCW...CCWWCC................',
  '.................................WWWW.......................WWW..KKKCWWWW.CCWWCC................',
  '............................CC...WWWW........................W.WKKKKWWppWW.CCCC.................',
  '...........................CCCC.WWWWWWW.......................WKKKKKKWppWW..CC..................',
  '..........................CCWWCCWWEEWWW.........HH...........KKKKK55KWWWW..FFF..................',
  '..........................CCWWCCWEEEEWWWW......HHHH........KKKKKK5kk5KKW.FFFFF..................',
  '...........................CCCCWWEEEEWWWWWHHHHHHHHHHHHKKKKKKKKKKK5kk5KKKFFMMFFvv................',
  '............................CCWEEEEEEEEWWWWHHHHHHHHHHKKKKKKKKKK55kkkk55KKFMMFFvv................',
  '...........................WWWEEEEEEEEEEWWWWiiiiHHHHHKKK55KKKK5kkkkkvv5KKFFFFF..................',
  '..........................WWWWEEEEEEEEEEWWWWiiiiHHHHKKKK55KKKK555555vvk5KKFFF...................',
  '..........................WWWWWWWWWWWWWWWWWWHHHHHHHHKKKKKKKKKKKKKKKKKKLLKKLL....................',
  '...........................WWWWWWWWWWWWWWWWHHHiHHHHHKKKKKKKKKKKKKKKKKKLLKKLL....................',
  '..............................HHHHHHHHiiiiHHHHHiHHHHKKKKKKKKKKKKKK55KKpp..LL....................',
  '.............................HHHHHHHHiHiiHHHHHHHiHHKKKKKKKKKKKKKKK55KKKp..LL....................',
  '.............................HHHHHHHHHiHHHHHHHHHHiKKKKKKKKKKKKKKKKKKKKKK..CC....................',
  '............................HHHHHHHHHHHiHHHHHHHHHHiKKKKKKKKKKKKKKKKKKKK...CC....................',
  '............................HHHHHHHHHHHHiHHHHHHHHHHKKKdKKKKKKKKKKKKKKKK.........................',
  '............................HHHHHHHHHHHHHiHHHHHHHHHHKKKdKKKKKKKKKKKKKK..........................',
  '............................HHHHHHHHHHHHHHiHHHHHHHHHKKKKdKKKKKKKKKKKKK..........................',
  '...........................HHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKK..........................',
  '...........................HHHHHHHHHHHHHHHddddHHHHHHKKKKKKddddKKKKKKKKH.........................',
  '..........................HHHHHHHHHHHHHHHHd2ddHHHHHHHKKKKKddddKKKKKKKKHH........................',
  '..........................HHHHHH11HHHHHH11H1HHHH11HHHKKKKKKKKKKKKKKKKK11........................',
  '..........................HHHHHH1h1HHHHH11HH1HHH11HHHHHKKKKKKKKKKKKKKKhh........................',
  '..........................HHHHHH1h1HHHHSSSBBy1SHHHHSSHHHSSBByKKKSSKKKH1h........................',
  '..........................HHHHH1hhh1HSSSSSBByySSHHSSSSHHSSBByyKKSSSKHH1h........................',
  '..........................HHHHH1hhhhSSSSSSBBYYBSSSSSSSSSSSBBYYBBSSSSSShh........................',
  '..........................HHHH1hhhhhhSSSWSBBYYBBSSSSSSSSSSBBYYBWSSSSSShh........................',
  '..........................HHHH1hhhhhhSSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSSH1h........................',
  '..........................HHHH1hhhhhhhSSSSBBYYBBSSSSSSSSSSBBYYBBSSSSHH1h........................',
  '..........................HHHH1hhhhhhhuuuuBBYYBBSSSSSSSSSSBBYYuuuuSSHH1h........................',
  '..........................HHHH1hhhhhhhuuuuBBYYBSSSSSSSSSSSSBYYuuuuSSHH1h........................',
  '..........................HHHH1hhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSHH1h........................',
  '..........................HHHH1hhhhhhhhSSSSSSSSSSSSSSSSSSSSSSSSSSSSHHH1h........................',
  '..........................HHHH1hh..hhhhSSSSSSSSSSSBBWWBBSSSSSSSSSSSHHH1h........................',
  '..........................HHHH1h.....hhhSSSSSSSSSSBBWWBBSSSSSSSSSSHHHH1h........................',
  '..........................HHHH1h.........SSSSSSSSSSSMMSSSSSSSSSSS.HHHH1h........................',
  '..........................HHH1h............SSSSSSSSSMMSSSSSSSSS....HHH1h........................',
  '..........................HH12h............SSSSSSSSS3s3SSSSSSSS...dHHH1h........................',
  '...........................H112.............SSSSSSSSS3s3SSSSS......dHH1.........................',
  '...........................HHH...........XRRRRRRRRRSSSRRXX..........HH..........................',
  '............................HH..........XXRRRRRRRRRRSSSRXX..........HH..........................',
  '............................FF...SSSSSSSSSSSSSggLLggSSSSSSSSSSSSS...FF..........................',
  '...........................FFFF.SSSSSSSSSSSSSSgLLLLgSSSSSSSSSSSSSS.FFFF.........................',
  '...........................FppFF3SSSSSSSSSSSSSLLLLLLSSSSSSSSSSSSS3FFppF.........................',
  '..........................FFppFFs3SSSSSSSSSSSSSLLLLSSSSSSSSSSSSS3sFFppFF........................',
  '.........................RXXGGGGGGGGGGGSSSSSSSSSBBSSSSSSSGGGGGGGGGGGGGXXR.......................',
  '........................RRRXGGGGGGGGGGGGSSSSSSSSBBSSSSSSGGGGGGGGGGGGGGXRRR......................',
  '........................RRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRR......................',
  '.......................RRRRRRROOOOOOOOOOSSSSSSSSSSSSSSSSOOOOOOOOOOOORRRRRRR.....................',
  '.....................XRRRX......GGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGG......XRRRX...................',
  '....................XXRRXX......GGGGGGGGSSSSSSSSSSSSSSSSGGGGGGGGGG......XXRRXX..................',
  '.................4wwwwwwwww....4wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww4.................',
  '................q4wwwwwwwwww..q4wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww4q................',
  '...............Gq4wwwwwwwwww..q4wwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww4qG...............',
  '..............GGq4wwwwwwwwww..q4wwwwPPwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww4qGG..............',
  '..............GGqqPPwwwwwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwPPwwww4qGG..............',
  '..............GGqPPPwwwwwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwPPPwwww4qGG..............',
  '..............GGPPwwppw4wwww..OOOOOOOOOOOOOOOOOOOOOORGGGLLGGLLGGGROOwwPP4wppww4qGG..............',
  '..............GGPPwwppw4wwww..OOOOOOOOOOOOOOOOOOOOOORRGLLLGGLLLGRRROwwPP4wppww4qGG..............',
  '..............GGqPPPwww4wwww..RRRRRRPPRRRRRRRRRRRRppRRLLLGRRGLLLRRRRwwwPqPwwww4qGG..............',
  '..............GGqqPPwww4wwww..RRRRRRPPRRRRRRRRRRRRppRRLLGGRRGGLLRRRRwwww4Pwwww4qGG..............',
  '..............GGq4wwwwP4wwww..RRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwww4wwwPPqqGG..............',
  '..............GGq4wwwPP4wwww..RRRRRRRRRRRRRRWWRRRRRRRRGGGGRRGGGGRRRRwwww4wwPPPqqGG..............',
  '..............GGq4wwPPwwppww..OOOOOOOOOOOOOOOOOOOOOOOOGGggGGggGGOOOOwwwwwwPPwwppGG..............',
  '..............GGq4wwPPwwppww..OOOOOOOOOOOOOOOOOOOOOOOGGGggGGggGGGOOOwwwwwwPPwwppGG..............',
  '..............GGq4wwwPPPwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwwwwwwwPwPqqGG..............',
  '...............GG4wwwwPPwwww..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGwGwwwwwwwPPqGG...............',
  '...............GGGGGGGGGGGGG..q4wwwwwwwwppwwwwRRwwRRwwwwwwOOOOOOOOwGwGGGGGGGGGGGG...............',
  '................GGGGGGGGGGGG..q4wwwwwwww4pwwwwRRww4RwwwwwwOOOOOOOOwwGGGGGGGGGGGG................',
  '................OOOOOOOOOOOO..q4wwwwwwwww4wwwwRRww4RwwwwwwOOGGOOppwwOOOOOOOOOOOO................',
  '.................OOOOOOOOOO...q4wwwwwwwwww4wwwRRww4RwwwwwwOOGGOpppwwwOOOOOOOOOO.................',
  '....................RRXXRR....q4wwwwwwwwwww4waaaww4CCwwwwwOOOOpppOwwww4qRRXXRR..................',
  '....................RXXXXR....q4wwwwwwwwwwwwaaaaww4CCCwwwwOOOOppOOwwww4qRXXXXR..................',
  '....................XXRRXX....q4wwwwwwwwwwwwpaaawwWCCCwwwwOOGGOOOOwwww4qXXRRXX..................',
  '....................XXRRXX....q4wwwwwwwwwwwwppaawwWWCCwwwwOOGGOOOOwwww4qXXRRXX..................',
  '....................RXXXXR....GGGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRXXXXR..................',
  '....................RRXXRR.....GGGGGGGGGGGGGGGGGGGGGGGGGGGOOOOOOOOGGGGGGRRXXRR..................',
  '...................ggg..ggg.................TTTTTTtt....TTTTTTtt....gggg..gggg..................',
  '..................gggg..gggg...........W....TTTTTTtt...WTTTTTTtt....gggg..gggg..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................LLLL..LLLL...........W....TTTTTTtt...WTTTTTTtt....LLLL..LLLL..................',
  '..................ggBB..ggBB................TTTTTTtt....TTTTTTtt....ggBB..ggBB..................',
  '..................ggBB..ggB.................TTTTTTtt....TTTTTTtt....ggBB..ggB...................',
  '..................RRXXRRXX..................TTTTTbtt....TTTTTbtt....RRXXRRXX....................',
  '..................RRXXRRXX..................TTTTbbtt....TTTTbbtt....RRXXRRXX....................',
  '..................RRXXRRXX.................rrrrrrrrrrrrrrrrrrrrrr...RRXXRRXX....................',
  '..................RRXXRRXX................rrrrrrrrrrrrrrrrrrrrrrrr..RRXXRRXX....................',
  '..................RRXXRRXX................bbbbbbbbbbbbbbbbbbbbbbbb..RRXXRRXX....................',
  '...................RXXRRX..................bbbbbbbbbbbbbbbbbbbbbb....RXXRRX.....................',
]
